export const CATEGORIES = [
  "Бизнес ба Менежмент",
  "Маркетинг ба Борлуулалт",
  "Мэдээллийн Технологи",
  "Дизайн ба Бүтээлч салбар",
  "Санхүү ба Нягтлан бодох бүртгэл",
  "Боловсрол ба Сургалт",
  "Эрүүл мэнд",
  "Барилга ба Инженерчлэл",
  "Худалдаа ба Үйлчилгээ",
  "Хууль ба Зөвлөх үйлчилгээ",
  "Тээвэр ба Логистик",
  "Урлаг ба Энтертайнмент",
  "Спорт ба Фитнесс",
  "Хөдөө аж ахуй",
  "Олон нийт",
  "Үл хөдлөх",
  "Үйлдвэрлэл",
  "ОУ харилцаа",
  "ТББ",
  "Хэвлэл мэдээлэл",
  "Шинжлэх ухаан",
  "Аялал жуулчлал",
  "Төрийн алба",
  "Оюутан / Эхлэн суралцагч",
  "Бусад"
];

export const SKILLS_SUGGESTIONS = [
  "Facebook Ads", "Google Ads", "SEO", "Content Writing", "Copywriting",
  "Graphic Design", "Logo Design", "UI/UX Design", "Web Design",
  "React Developer", "Node.js Developer", "Python", "Java", "C++",
  "Data Analysis", "Machine Learning", "AI Prompt Engineering",
  "Accounting", "Financial Planning", "Tax Consulting",
  "Plumbing", "Electrical Work", "Carpentry", "Painting",
  "Project Management", "Business Strategy", "Sales Coaching",
  "Translation", "Language Teaching", "Tutoring",
  "Photography", "Videography", "Video Editing",
  "Personal Training", "Yoga Instructor", "Nutritionist"
];
